Sprint 13
Sucheit/java-shareit pull request #1
Opened 2023-05-21 12:37 UTC by Sucheit

2023-05-22 12:39 UTC, mikita95 requested changes
Все отлично. Оставил лишь пару замечаний

2023-05-22 12:39 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/model/ItemEntity.java
> +    @OneToOne
В данной версии задания достаточно было хранить данные в памяти, но так тоже просто отлично :) Еще и hibernate подключили. Однако здесь должно быть другое отношение, у одного пользователя может быть несколько объектов

2023-05-22 12:39 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<ItemEntity> findByUserEntity(UserEntity userEntity);
Здесь достаточно id пользователя

2023-05-22 16:17 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<ItemEntity> findByUserEntity(UserEntity userEntity);
исправлено

2023-05-22 16:18 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/item/model/ItemEntity.java
> +    @OneToOne
исправлено

2023-05-23 13:19 UTC, mikita95 approved these changes
Все сделано верно. Можно мержить :)

2023-05-24 05:38 UTC, merged