Техническое задание проекта №14
Sucheit/java-shareit pull request #2
Opened 2023-05-30 07:52 UTC by Sucheit

2023-05-31 08:44 UTC, mikita95 requested changes
Все сделано хорошо. Однако, нужно добавить еще схему базы данных. А также использовать транзакции.

2023-05-31 08:44 UTC, mikita95 commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/share-it
В задании сказано: Напишите SQL-код для создания всех таблиц и сохраните его в файле resources/schema.sql.
Здесь нужно использовать postgreSql, а не h2

2023-05-31 08:44 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (optionalBookingEntity.isEmpty()) {
Можно в таком случае просто использовать orElseThrow в Optional, чтобы не делать отдельное ветвление

2023-05-31 08:44 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +public class BookingService {
Нужно использовать транзакции спринга, чтобы объединить эти опирации в транзакции, ведь на каждом шаге может что-то произойти, что база данных останется в несогласованном виде

2023-05-31 08:44 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                        .filter(bookingEntity -> bookingEntity.getStatus().equals(Status.WAITING));
Все эти фильтрации лучше выполнять в базе данных, так будет намного эффективнее, что фильтровать в памяти

2023-06-03 15:24 UTC, Sucheit commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/share-it
исправлено

2023-06-03 15:25 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (optionalBookingEntity.isEmpty()) {
исправлено

2023-06-03 15:25 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +public class BookingService {
исправлено

2023-06-03 15:25 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                        .filter(bookingEntity -> bookingEntity.getStatus().equals(Status.WAITING));
исправлено

2023-06-04 11:12 UTC, mikita95 requested changes
Все сделано отлично. Оставил несколько замечаний, которые не трудно будет поправить, думаю

2023-06-04 11:12 UTC, mikita95 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS public.items (
Можно добавить еще ограничение на уникальность (item_id, name)

2023-06-04 11:12 UTC, mikita95 commented on src/main/resources/schema.sql
> +	user_id BIGINT NULL,
У айтема всегда должен быть пользователь, то есть лучше использовать NOT NULL

2023-06-04 11:12 UTC, mikita95 commented on src/main/resources/schema.sql
> +	name varchar(255) NULL,
Имя и почты должны быть всегда, лучше использовать NOT NULL

2023-06-04 11:12 UTC, mikita95 commented on src/main/resources/schema.sql
> +	created timestamp NULL,
Время должно быть всегда, лучше пометить как NOT NULL

2023-06-04 11:12 UTC, mikita95 commented on src/main/resources/schema.sql
> +	text varchar(255) NULL,
Текст комментария должен быть всегда, лучше пометить как NOT NULL

2023-06-04 11:12 UTC, mikita95 commented on src/main/resources/schema.sql
> +CREATE TABLE public.bookings (
Лучше использовать CREATE TABLE IF NOT EXISTS - это поможет избежать разных проблем

2023-06-04 11:12 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      private UserEntity userEntity;
dto, который отдаются наружу, не должны содержить jpa-сущностей, здесь нужно использовать dto или id просто. Либо в dto можно обойтись без пользователя вообще

2023-06-04 11:12 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private ItemEntity item;
В dto не нужно использовать jpa-сущности, лучше использовать отдельные dto

2023-06-04 11:12 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private UserEntity booker;
В dto не нужно использовать jpa-сущности, лучше использовать отдельные dto

2023-06-04 15:31 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Transactional
исправлено

2023-06-04 15:31 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    @Transactional
исправлено

2023-06-04 15:36 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    @RequestParam(value = "approved") String approved,
исправлено

2023-06-04 15:41 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto updateBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
исправлено

2023-06-04 15:43 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/model/BookingEntity.java
> +    private LocalDateTime startTime;
исправлено

2023-06-04 15:44 UTC, Sucheit commented on src/main/resources/schema.sql
> +	text varchar(255) NULL,
исправлено

2023-06-04 15:45 UTC, Sucheit commented on src/main/resources/schema.sql
> +CREATE TABLE public.bookings (
исправлено

2023-06-04 15:47 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      private UserEntity userEntity;
исправлено

2023-06-04 16:14 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private UserEntity booker;
исправлено

2023-06-04 16:14 UTC, Sucheit commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private ItemEntity item;
исправлено

2023-06-04 18:41 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-06-04 19:19 UTC, merged